export const registerFields = [
  {
    id: 1,
    name: 'Nombre',
    field: 'name',
    type: 'text',
    icon: 'fa-user',
    errorMessage: 'El nombre es obligatorio',
  },
  {
    id: 2,
    name: 'Apellido',
    field: 'lastName',
    type: 'text',
    icon: 'fa-user',
    errorMessage: 'El apellido es obligatorio',
  },
  {
    id: 3,
    name: 'Telefono',
    field: 'phone',
    type: 'number',
    icon: 'fa-mobile-alt',
    errorMessage: 'El telefono es obligatorio',
  },
  {
    id: 4,
    name: 'Correo electronico',
    field: 'email',
    icon: 'fa-envelope',
    errorMessage: 'El correo electronico es obligatorio',
  },
  {
    id: 5,
    name: 'Contraseña',
    field: 'password',
    type: 'password',
    icon: 'fa-lock',
    errorMessage: 'La contraseña es obligatorio',
  },
  {
    id: 6,
    name: 'Direccion',
    field: 'address',
    type: 'text',
    icon: 'fa-map-marker-alt',
    errorMessage: 'La direccion es obligatorio',
  },
];
